// Add your dependencies here

dependencies {
    api("com.github.GTNewHorizons:GTNHLib:0.11.40:dev")
    compileOnlyApi('com.github.GTNewHorizons:Angelica:2.2.7:dev')
    compileOnly("com.github.GTNewHorizons:Postea:1.2.6:dev") {transitive = false}
    
    runtimeOnlyNonPublishable('com.github.GTNewHorizons:NotEnoughItems:2.8.125-GTNH:dev')
    devOnlyNonPublishable('com.github.GTNewHorizons:waila:1.19.31:dev')
}
